name: ini_file
description: get, set, create, delete sections, keys, values from ini file, without loosing its format, blank lines, comments, etc.
version: 0.0.2-beta
# homepage: https://www.example.com

repository: https://github.com/GnRSlash/ini_file
issue_tracker: https://github.com/GnRSlash/ini_file/issues

environment:
  sdk: '>=2.13.0-134.5.beta <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
